include colors.conf

font_family      JetBrainsMono Nerd Font Mono

font_size       10.0

disable_ligatures never
enable_audio_bell no

# cursor_shape block
url_style curly

scrollback_lines 2000

scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

remember_window_size no

window_padding_width 10

background_opacity 0.49

scrollbar_handle_opacity 0

cursor_trail 200

