
# ---------------------------------------------------------
# Tema Personalizado - Tonos Violeta/Nocturno
# ---------------------------------------------------------

# --- Colores Generales ---
foreground           #e6dfff
background           #0c0017
selection_foreground #ffffff
selection_background #4b0082
url_color            #df00ff

# --- Cursor ---
cursor               #8a2be2
cursor_text_color    #ffffff

# --- Paleta ANSI ---

# Black (Tonos oscuros violeta)
color0 #17002e
color8 #2e005c

# Red (Rojos rosados para encajar con el tono)
color1 #d93a7d
color9 #ff57a0

# Green (Menta/Turquesa para contraste)
color2  #198b76
# color2  #15674f
# color2  #29b69b

color10 #3de0c2

# Yellow (Dorados suaves)
color3  #e3b854
color11 #ffcf5e

# Blue (Tus azules/índigos profundos)
color4  #8b9bf2
color12 #b1bdf8

# Magenta (Tus morados y fucsias brillantes)
color5  #8a2be2
color13 #df00ff

# Cyan (Cian brillante para legibilidad)
 color6  #00b4d8
 color14 #00d4ff

# White (Blancos con ligero tinte lavanda)
color7  #d1c4e9
color15 #ede7f6