require("modules.monitors")
require("modules.autostart")
require("modules.environment_variables")
-- require("modules.permissions")
require("modules.keybindings")
require("modules.colors")
require("modules.animations")
require("modules.input")
require("modules.windows")