# ---------------------------------------------------------
# Custom Theme - Everforest (Green Dominant)
# ---------------------------------------------------------

foreground           #D3C6AA
background           #272E33
selection_foreground #D3C6AA
selection_background #3C4841
url_color            #A7C080

cursor               #A7C080
cursor_text_color    #272E33

# Black
color0 #374145
color8 #859289

# Red
color1 #E67E80
color9 #E67E80

# Green
color2  #A7C080
color10 #A7C080

# Yellow
color3  #DBBC7F
color11 #DBBC7F

# Blue
color4  #7FBBB3
color12 #7FBBB3

# Magenta (Purple)
color5  #D699B6
color13 #D699B6

# Cyan (Aqua)
color6  #83C092
color14 #83C092

# White
color7  #9DA9A0
color15 #D3C6AA
