add_newline = false

format = """
[](fg:#A7C080)\
$username\
[](fg:#A7C080 bg:#3C4841)\
$directory\
[](fg:#3C4841)\
$character
"""

[username]
show_always = true
style_user = "bg:#A7C080 fg:#272E33"
format = "[$user]($style)"

[directory]
style = "bg:#3C4841 fg:#D3C6AA"
format = "[ $path ]($style)"
truncation_length = 3

[character]
success_symbol = "[ ➜ ](bold #A7C080)"
error_symbol = "[ ✗ ](bold #E67E80)"
